// blogConstants.js

export const CREATE_BLOG_REQUEST = 'CREATE_BLOG_REQUEST';
export const CREATE_BLOG_SUCCESS = 'CREATE_BLOG_SUCCESS';
export const CREATE_BLOG_FAILURE = 'CREATE_BLOG_FAILURE';

export const GET_ALL_BLOGS_REQUEST = 'GET_ALL_BLOGS_REQUEST';
export const GET_ALL_BLOGS_SUCCESS = 'GET_ALL_BLOGS_SUCCESS';
export const GET_ALL_BLOGS_FAILURE = 'GET_ALL_BLOGS_FAILURE';

export const GET_BLOG_BY_ID_REQUEST = 'GET_BLOG_BY_ID_REQUEST';
export const GET_BLOG_BY_ID_SUCCESS = 'GET_BLOG_BY_ID_SUCCESS';
export const GET_BLOG_BY_ID_FAILURE = 'GET_BLOG_BY_ID_FAILURE';

export const UPDATE_BLOG_REQUEST = 'UPDATE_BLOG_REQUEST';
export const UPDATE_BLOG_SUCCESS = 'UPDATE_BLOG_SUCCESS';
export const UPDATE_BLOG_RESET   = 'UPDATE_BLOG_RESET';
export const UPDATE_BLOG_FAILURE = 'UPDATE_BLOG_FAILURE';

export const DELETE_BLOG_REQUEST = 'DELETE_BLOG_REQUEST';
export const DELETE_BLOG_SUCCESS = 'DELETE_BLOG_SUCCESS';
export const DELETE_BLOG_RESET   = 'DELETE_BLOG_RESET';
export const DELETE_BLOG_FAILURE = 'DELETE_BLOG_FAILURE';

export const CLEAR_ERRORS = "CLEAR_ERRORS";